- name: Sync system time
  service:
    name: systemd-timesyncd
    state: restarted

- name: Install Packages
  apt:
    pkg:
      - apache2
      - apache2-utils
      - ruby
      - ruby-dev
      - make
      - libssl-dev
      - zlib1g-dev
      - libicu-dev
      - build-essential
      - git
      - cmake
      - pkg-config
    force_apt_get: true
    update_cache: yes
